name: Build

on:
  push:
    paths: ['testrom/*.c']
  pull_request:
    paths: ['testrom/*.c']

jobs:
  build:
    runs-on: ubuntu-latest
    container: z88dk/z88dk

    steps:
    - uses: actions/checkout@v6

    - name: Build with z88dk
      working-directory: testrom
      run: ./build.sh

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v6
      with:
        name: testromc
        path: testrom/a.rom
