name: Build

on:
  push:
    paths: ['testrom/*.c']
  pull_request:
    paths: ['testrom/*.c']

jobs:
  build:
    runs-on: ubuntu-latest
    container: z88dk/z88dk

    steps:
    - uses: actions/checkout@v6

    - name: Build with z88dk
      working-directory: testrom
      run: zcc +z80 -clib=8085 -pragma-define:CRT_ORG_BSS=0xc000 -pragma-define:REGISTER_SP=0xc7f0 main.c -create-app

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v6
      with:
        name: testromc
        path: testrom/a.rom
